### ISSUE TITLE
Prerequisites

### ISSUE THREAD

**Issue by Yingxiu-Chang** [batuhan3526/AirSim-PyTorch-Drone-DDQN-Agent#1]
Hello, @batuhan3526 
I have keen interests of this work. Could you please tell the version requirements of packages and dependencies of it. 
Best Regards
Hugh

**Comment by batuhan3526** [comment]
python 3.8, CUDA 10.1 (maybe 10.2), Torch 1.7. And sorry for my delay

**Comment by batuhan3526** [comment]
@Hugh-Chang Pls check it readme file. I was going to add Readme for a long time. I was able to do that just now. Sorry for delay again

**Comment by Yingxiu-Chang** [comment]
Thank you so much for your help. It works for me.
All the best


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
21/03/29下午11:44:47
